apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  labels:
    app: {{ .Release.Name }}-mysql
    {{- include "crud-app.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.mysql.port }}
    targetPort: {{ .Values.mysql.port }}
  selector:
    app: {{ .Release.Name }}-mysql
  type: {{ .Values.mysql.service.type }}
