{{- if .Values.mysql.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "crud-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mysql.auth.username | b64enc }}
  password: {{ .Values.mysql.auth.password | b64enc }}
{{- end }}
