apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  labels:
    release: prometheus
    {{- include "crud-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-crud-app  # Ensure this matches your service label
  endpoints:
    - port: metrics  # This should match the metrics port name in your Service
      path: {{ .Values.metrics.path }}
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
